Module1 task1 Разметка мобильных версий страниц сайта
sasstr/11223377_cat_energy pull request #2
Opened 2018-04-12 05:16 UTC by sasstr

Разметил мобильные версии страниц сайта

2018-04-12 07:02 UTC, 4err requested changes
Одинаковые замечания не повторяю, все актуально для всех файлов.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +                <div class="navigation-logo__image"></div>
А картинка где?

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +              <div class="main-navigation__logo navigation-logo">
Логотип может оказаться и в другом месте, а не только навигации. Как самостоятельный блок лучше не привязывать его к навигации. Для этого у тебя есть класс `main-navigation__logo` он как раз будет отвечать за поведение блока логотипа как элемента навигации.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +                <a class="navigation-list__item_link" href="index.html">Главная</a>
Везде используются дефисы, а тут почему-то единичное нижнее подчеркивание. Здесь и далее.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +       <main class="catalog-main-content">
Выделять контентную область как уникальные блоки на разных страницах не стоит. Как правило они все-таки имеют какую-то общую структуру. Здесь можно воспользоваться какими-то техническими классами.

У тебя получается контентная область должна состоять из независимых блочков, как кубиков.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +          <h1 class="catalog-items__title">Каталог продукции</h1>
Данный заголовок является общим для второстепенных страниц, поэтому его лучше оформить отдельным БЭМ блоком и вынести из этой секции.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +          <div class="catalog-items__product catalog-item">
Для карточки товара лучше использовать `article`.  Это независмысый смысловой блок который может быть размещен где угодно.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +            <h3 class="catalog-item__title">Cat energy<br>pro 500 г</h3>
`br` лишние .

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +              <tr class="item-description__option description-option">
БЭМ блоки должны быть независмысми. Я слабо представляю использование `tr` блоков вне таблицы. Думаю здесь этот БЭМ блок лишний.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +            <button class="catalog-item__order-button" type="button">Заказать</button>
ссылка же!

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +          <div class="catalog-items__product catalog-item">
По остальным товарам аналогично.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +            <h3 class="catalog-item-add__title">Сахаразаменитель</h3>
Тут `catalog-item-add__title` и вверху такой же блок где 100500 товаров. А блоки разные.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +            <a class="item-add-promo__link" href="#">
А с чего ты взял что это ссылка?

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +            <img src="http://placehold.it/140x144" height="144" width="140" alt="Товар Cat Energy PRO 500 г Курица">
По ТЗ название и картинка являются ссылкой.

2018-04-12 07:02 UTC, 4err commented on source/catalog.html
> +          <div class="main-footer">
Блок такой же как и весь футер. Что-то мне подсказывает что это непраивльно.

2018-04-12 07:02 UTC, 4err commented on source/form.html
> +            <input type="radio" name="lose-weight" id="lose-weight" checked> <!-- class="visually-hidden"-->
У радиобаттонов должны быть одинаковые имена, иначе оно не будте работать.

2018-04-12 07:02 UTC, 4err commented on source/form.html
> +            <label  class="form-info__programm-type" for="lose-weight">Похудение</label>
Классы все-таки должны быть привязаны не к конкретному контенту. Здесь их следует привязать к типу полей.

2018-04-12 07:02 UTC, 4err commented on source/form.html
> +            <input class="form-info__contacts-data" type="email" name="email" id="email">
Отличный пример. Текстовые поля идентичные тем, что указаны ранее, однако почему-то другие классы.

2018-04-12 07:02 UTC, 4err commented on source/index.html
> +         <ul class="catalog-items__list items-list">
У тебя уже есть блок catalog-items в каталоге. Ты уверен что здесь оно такое же?

2018-04-12 07:02 UTC, 4err commented on source/index.html
> +            <div class="features__item feature-item">
У всех фич разные картиночки. Нужны классы модификаторы для них.

2018-04-12 07:02 UTC, 4err commented on source/index.html
> +          <form class="example__switch example-switch" action="echo.htmlacademy.ru">
Если ты используешь инпуты для функционала, форма не нужна.

2018-04-12 07:02 UTC, 4err commented on source/index.html
> +            <label class="example-switch__now" for="now">Стало</label>
почему у лейблов разные классы? Вероятно он должен быть один но с разными модификаторами.

2018-04-12 07:02 UTC, 4err commented on source/index.html
> +            <input type="radio" name="now" id="now">
Опять некорректные имена у радиобаттонов.

2018-04-12 08:53 UTC, sasstr commented on source/index.html
> +            <div class="features__item feature-item">
Вот точно про это вспоминал пока на работу ехал

2018-04-13 06:09 UTC, sasstr commented on source/catalog.html
> +                <a class="navigation-list__item_link" href="index.html">Главная</a>
Исправил

2018-04-13 06:09 UTC, sasstr commented on source/catalog.html
> +                <div class="navigation-logo__image"></div>
Исправил

2018-04-13 06:33 UTC, sasstr commented on source/catalog.html
> +              <div class="main-navigation__logo navigation-logo">
Исправил

2018-04-13 06:38 UTC, sasstr commented on source/catalog.html
> +       <main class="catalog-main-content">
Исправил

2018-04-13 06:44 UTC, sasstr commented on source/catalog.html
> +          <h1 class="catalog-items__title">Каталог продукции</h1>
Исправил

2018-04-13 06:46 UTC, sasstr commented on source/index.html
> +         <ul class="catalog-items__list items-list">
Исправил

2018-04-13 06:52 UTC, sasstr commented on source/index.html
> +            <div class="features__item feature-item">
Исправил

2018-04-13 06:53 UTC, sasstr commented on source/index.html
> +          <form class="example__switch example-switch" action="echo.htmlacademy.ru">
Исправил

2018-04-13 06:57 UTC, sasstr commented on source/index.html
> +            <label class="example-switch__now" for="now">Стало</label>
Исправил

2018-04-13 07:11 UTC, sasstr commented on source/index.html
> +            <input type="radio" name="now" id="now">
Исправил

2018-04-13 07:57 UTC, sasstr commented on source/catalog.html
> +            <h3 class="catalog-item__title">Cat energy<br>pro 500 г</h3>
Исправил

2018-04-13 08:24 UTC, sasstr commented on source/catalog.html
> +          <div class="catalog-items__product catalog-item">
Исправил

2018-04-13 08:35 UTC, sasstr commented on source/catalog.html
> +              <tr class="item-description__option description-option">
Исправил

2018-04-13 10:45 UTC, sasstr commented on source/catalog.html
> +            <button class="catalog-item__order-button" type="button">Заказать</button>
Исправил

2018-04-13 10:45 UTC, sasstr commented on source/catalog.html
> +          <div class="catalog-items__product catalog-item">
Исправил

2018-04-13 11:01 UTC, sasstr commented on source/catalog.html
> +                <div class="navigation-logo__image"></div>
Исправил

2018-04-13 11:01 UTC, sasstr commented on source/catalog.html
> +              <div class="main-navigation__logo navigation-logo">
Исправил

2018-04-13 11:01 UTC, sasstr commented on source/catalog.html
> +                <a class="navigation-list__item_link" href="index.html">Главная</a>
Исправил

2018-04-13 11:01 UTC, sasstr commented on source/catalog.html
> +       <main class="catalog-main-content">
Исправил

2018-04-13 11:09 UTC, sasstr commented on source/catalog.html
> +            <h3 class="catalog-item-add__title">Сахаразаменитель</h3>
Исправил

2018-04-13 11:10 UTC, sasstr commented on source/catalog.html
> +            <a class="item-add-promo__link" href="#">
Исправил

2018-04-13 14:31 UTC, sasstr commented on source/form.html
> +            <input type="radio" name="lose-weight" id="lose-weight" checked> <!-- class="visually-hidden"-->
Исправил

2018-04-13 14:45 UTC, sasstr commented on source/catalog.html
> +          <div class="main-footer">
Исправил

2018-04-13 15:15 UTC, sasstr commented on source/form.html
> +            <input class="form-info__contacts-data" type="email" name="email" id="email">
Исправил

2018-04-14 12:44 UTC, 4err requested changes

2018-04-14 12:44 UTC, 4err commented on source/form.html
> +        <label class="form-info__name form-info--state" for="cat-name">Имя:*</label>
Здесь и далее. Класс модификатор не может использоваться без модифицируемого элемента.

Также с именованием классов, лучше опираться на тип полей, а не содержимое.
класс `form-info__name` смотрится очень странно на поле о возрасте. А если форма увеличится у нас добавится поле увлечения, а класс все еще name? Это вносит путаницу.
Помимо этого все текстовые инпуты являются одинаковыми, незачем им разные классы. Если используется какое-то незначительное отличие, следует использовать модификатор.
Соответственно, чтобы избежать всех этих проблем, лучше задавать классы опираясь на типы полей: form__label, form__text-input, form_radio и тп.

По такому принципу нужно исправить всю форму.

2018-04-14 12:44 UTC, 4err commented on source/catalog.html
> +            <a class="navigation-list__item-link" >Каталог продукции</a>
Какой-то класс для выделения текущей страницы наверное должен быть.

2018-04-14 16:46 UTC, sasstr commented on source/catalog.html
> +            <a class="navigation-list__item-link" >Каталог продукции</a>
Исправил

2018-04-14 17:27 UTC, sasstr commented on source/form.html
> +        <label class="form-info__name form-info--state" for="cat-name">Имя:*</label>
Исправил

2018-04-15 16:36 UTC, merged